version: '3.9'

services:
  webapp:
    restart: always
    #image: postgre-dotnet-app:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      qwert: asdasd
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: weather_db
      POSTGRES_USER: aleksejs
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
          
volumes:
  pg_data: